{% set version = "0.7.3" %}

package:
  name: yaml2ncml
  version: {{ version }}

source:
  url: https://github.com/USGS-CMG/yaml2ncml/archive/v{{ version }}.tar.gz
  sha256: 238654fb5ebe2b95a64dc0de4fd398eb7a18a416d8664616065f96617a1267b6

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - yaml2ncml = yaml2ncml.yaml2ncml:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - docopt
    - netcdf4
    - ruamel.yaml

test:
  requires:
    - python {{ python_min }}
  imports:
    - yaml2ncml
  commands:
    - yaml2ncml --version

about:
  home: https://github.com/usgs-cmg/yaml2ncml
  license: MIT
  license_file: LICENSE.txt
  summary: NcML aggregation from YAML specification.

extra:
  recipe-maintainers:
    - ocefpaf
    - rsignell-usgs
