{% set version = "0.7.2" %}

package:
  name: yaml2ncml
  version: {{ version }}

source:
  url: https://github.com/USGS-CMG/yaml2ncml/archive/v{{ version }}.tar.gz
  sha256: d9fd6841d4f168c306bc331af64469811d4794b3500801d06ffe32c580c51c6b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - yaml2ncml = yaml2ncml.yaml2ncml:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - docopt
    - netcdf4
    - ruamel.yaml

test:
  imports:
    - yaml2ncml
  commands:
    - yaml2ncml --version

about:
  home: https://github.com/usgs-cmg/yaml2ncml
  license: MIT
  license_file: LICENSE.txt
  summary: NcML aggregation from YAML specification.

extra:
  recipe-maintainers:
    - ocefpaf
    - rsignell-usgs
