{% set version = "0.7.1" %}

package:
  name: yaml2ncml
  version: {{ version }}

source:
  url: https://github.com/USGS-CMG/yaml2ncml/archive/v{{ version }}.tar.gz
  sha256: 5544d4835907e0fe2d42bde7418ca2b4b7a52169dd8d649fe7b5a6e705006dca

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - docopt
    - netcdf4
    - ruamel.yaml
    - six

test:
  imports:
    - yaml2ncml
  commands:
    - yaml2ncml --version

about:
  home: https://github.com/usgs-cmg/yaml2ncml
  license: MIT
  license_file: LICENSE.txt
  summary: 'NcML aggregation from YAML specification.'

extra:
  recipe-maintainers:
    - ocefpaf
    - rsignell-usgs
