travis:
  secure:
    BINSTAR_TOKEN: jTbj8S+L83X10BGBCwmyAITbqv9tVOrW64SwjJloWeI1tKHkcQ4Syy+t9YWvs8VL0V1nsA6h0aJ+rqJOWfaSvze46qHBqp7IH2FeLYKEQ8Jt0ci4X4jZ97+sgzKDTGmb9EZTfccc2+cfEkIkj8f1AV8whuoUIL09kYCC9GznKbyKQkp3LWvzjw1OGf+Qy3C2ZZHNhr3ychSL3qmUx4fTY3RjokvQyHpd4mhPZiP6Tj77zWcHjzQOXFmUv8Xdg2+D+/ugG2QET9UiCk0PX9uIb2A9WNhh4+ZRZQS2yG/Qujpx5xFGD0b6u9clZO9CMXL815DnnWYV1+ltOGXh7lfaK/dHMntou7VL4jkZkHntMWU5zaUT7kV5fkQiNXIW91pYLcNNF2ig/nzNbCbb+421NUjBzglJdaoNrjXG4puHiitI95qpKl94ZEupHaJwgnaRHI0zVbkPjtwgh5fxUCbCYavdhqpN1g37d2jOw2K3q5Lf8kJzpbYQt2wg7f3v4FuCsTqJhUBh60/qf8fS2tvbC/R4ywarKGtuUOEIBFpUZUyXK2Ttv5+HHDWERsSQy+agV9CtKs0NcWQ3wbuL57dsxWjbevFb+kokFlD41PW46tFOfP1qrPra0YHrPy2FNi0PupKszblGzIELXEmdCIahdyYBdffIjmQhqlKGnG0IUBA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
